
// export const ROWS_TRANSACTION = [
//       {
//         transactionId:1,
//         transactionType: "Earn",
//         ratingType: "Slots",
//         earningDate: "7/12/2010",
//         dollarAmount: " 1.27",
//         property: "MSCT",
//         revenueCenter: "-",
//         balance: "123.76",
//         earningTime: "12:20:07",
//         reason: "-",
//         details: "-"
//       },
//       {
          
//           transactionId:2,
//           transactionType: "Redeem",
//           ratingType: "-",
//           earningDate: "7/12/2023",
//           dollarAmount: "(24.99)",
//           property: "MSCT",
//           revenueCenter: "SEP",
//           balance: "122.49",
//           earningTime: "11:43:10",
//           reason: "-",
//           details: "-"
//         },
//         {
          
//         transactionId:3,
//           transactionType: "Redeem",
//           ratingType: "-",
//           earningDate: "7/12/2023",
//           dollarAmount: " (5.25)",
//           property: "MSCLV",
//           revenueCenter: "MSCT",
//           balance: "147.48",
//           earningTime: "10:50:00",
//           reason: "-",
//           details: "-"
//         },
//         {
  
//           transactionId:4,
//           transactionType: "Earn",
//           ratingType: "Slot",
//           earningDate: "7/12/2023",
//           dollarAmount: " 6.54 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: "152.73",
//           earningTime: "9:35:55",
//           reason: "-",
//           details: "-"
//         },
//         {        
//         transactionId:5,
//           transactionType: "Earn",
//           ratingType: "Slot",
//           earningDate: "7/12/2023",
//           dollarAmount: "3.35",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 146.19 ",
//           earningTime: "8:43:59",
//           reason: "-",
//           details: "-"
//         },
//         {        
//         transactionId:6,
//           transactionType: "Adjustment",
//           ratingType: "Other",
//           earningDate: "7/12/2023",
//           dollarAmount: " 10.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: "142.84",
//           earningTime: "8:29:59",
//           reason: "Marketing Offer",
//           details: "-"
//         },
//         {        
//         transactionId:7,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "7/12/2023",
//           dollarAmount:" 73.73 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 132.84 ",
//           earningTime: "8:00:00",
//           reason: "Purge Reimbursement",
//           details: "TM#307031"
//         },
//         {        
//           transactionId:8,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "6/30/2023",
//           dollarAmount: " (73.73)",
//           property: "Corporate",
//           revenueCenter: "-",
//           balance: " 59.11 ",
//           earningTime: "6:00:00",
//           reason: "Inactive Purge",
//           details: "-"
//         },
//         {        
//           transactionId:9,
//           transactionType: "Redeem",
//           ratingType: "-",
//           earningDate: "6/25/2022",
//           dollarAmount: " (75.00)",
//           property: "MCLV",
//           revenueCenter: "MJS",
//           balance: " 132.84 ",
//           earningTime: "19:25:51",
//           reason: "-",
//           details: "-"
//         },
//         {        
//         transactionId:10,
//           transactionType: "Adjustment",
//           ratingType: "Achiever",
//           earningDate: "6/25/2022",
//           dollarAmount: " 50.00 ",
//           property: "MCLV",
//           revenueCenter: "-",
//           balance: " 207.84 ",
//           earningTime: "15:52:15",
//           reason: "Property Adj",
//           details: "Rule ID?"
//         },
//         {        
//           transactionId:11,
//           transactionType: "Earn",
//           ratingType: "-",
//           earningDate: "2/1/2023",
//           dollarAmount:"",
//           property: "MSCLV",
//           revenueCenter: "ABC",
//           balance: " 8.70 ",
//           earningTime: "11:50:00",
//           reason: "-",
//           details: "-"
//         },
//         {        
//           transactionId:12,
//           transactionType: "Earn",
//           ratingType: "Table",
//           earningDate: "6/25/2022",
//           dollarAmount:" 23.45 ",
//           property: "MCLV",
//           revenueCenter: "-",
//           balance: "157.84",
//           earningTime: "-",
//           reason: "-",
//           details: "-"
//         },
//         {        
//           transactionId:13,
//           transactionType: "Earn",
//           ratingType: "Table",
//           earningDate: "6/24/2022",
//           dollarAmount:"19.34",
//           property: "MCLV",
//           revenueCenter: "-",
//           balance: " 134.39 ",
//           earningTime: "-",
//           reason: "-",
//           details: "-"
//         },
//         {        
//           transactionId:14,
//           transactionType: "Earn",
//           ratingType: "Digital",
//           earningDate: "5/21/2022",
//           dollarAmount:" 1.63 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 115.05 ",
//           earningTime: "-",
//           reason: "-",
//           details: "-"
//         },
//         {        
//           transactionId:15,
//           transactionType: "Earn",
//           ratingType: "Table",
//           earningDate: "5/15/2022",
//           dollarAmount:" 30.47 ",
//           property: "MCLV",
//           revenueCenter: "-",
//           balance: " 113.42 ",
//           earningTime: "-",
//           reason: "-",
//           details: "-"
//         },
//         {        
//           transactionId:16,
//           transactionType: "Adjustment",
//           ratingType: "Other",
//           earningDate: "5/15/2022",
//           dollarAmount:" 15.00 ",
//           property: "MCLV",
//           revenueCenter: "-",
//           balance: " 82.95 ",
//           earningTime: "21:35:55",
//           reason: "Marketing Offer",
//           details: "-"
//         },
//         {        
//           transactionId:17,
//           transactionType: "Earn",
//           ratingType: "Digital",
//           earningDate: "5/11/2022",
//           dollarAmount:" 2.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 67.95 ",
//           earningTime: "-",
//           reason: "-",
//           details: "-"
//         },
//         {        
//           transactionId:18,
//           transactionType: "Earn",
//           ratingType: "Slot",
//           earningDate: "5/11/2022",
//           dollarAmount:" 4.24 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 65.95 ",
//           earningTime: "11:50:00",
//           reason: "-",
//           details: "-"
//         },
//         {        
//           transactionId:19,
//           transactionType: "Void",
//           ratingType: "-",
//           earningDate: "5/11/2022",
//           dollarAmount:" (3.00)",
//           property: "MPA",
//           revenueCenter: "-",
//           balance: " 61.71 ",
//           earningTime: "15:35:55",
//           reason: "Void Earning",
//           details: "Per Racebook"
//         },
//         {        
//           transactionId:20,
//           transactionType: "Earn",
//           ratingType: "Racebook",
//           earningDate: "5/11/2022",
//           dollarAmount:" 5.00 ",
//           property: "MPA",
//           revenueCenter: "-",
//           balance: "64.71",
//           earningTime: "-",
//           reason: "-",
//           details: "-"
//         },
//         {        
//           transactionId:21,
//           transactionType: "Earn",
//           ratingType: "Slot",
//           earningDate: "4/28/2022",
//           dollarAmount:" 0.10 ",
//           property: "ILANI",
//           revenueCenter: "-",
//           balance: "59.71",
//           earningTime: "-",
//           reason: "-",
//           details: "-"
//         },
//         {        
//           transactionId:22,
//           transactionType: "Earn",
//           ratingType: "Poker",
//           earningDate: "4/10/2022",
//           dollarAmount:"6.31",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 59.61 ",
//           earningTime: "-",
//           reason: "-",
//           details: "-"
//         },
//         {        
//           transactionId:23,
//           transactionType: "Earn",
//           ratingType: "Slot",
//           earningDate: "4/10/2022",
//           dollarAmount:" 4.33 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 53.30 ",
//           earningTime: "-",
//           reason: "-",
//           details: "-"
//         },
//         {        
//           transactionId:24,
//           transactionType: "Redeem",
//           ratingType: "-",
//           earningDate: "4/10/2022",
//           dollarAmount:" (50.03)",
//           property: "MSCT",
//           revenueCenter: "GAS",
//           balance: " 48.97 ",
//           earningTime: "13:25:51",
//           reason: "-",
//           details: "-"
//         },
//         {        
//           transactionId:25,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:26,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:27,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:28,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:29,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:30,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:31,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:32,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:33,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:34,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:35,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:36,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:37,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:38,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:39,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:40,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:41,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:42,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:43,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:44,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:45,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:46,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:47,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:48,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:49,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:50,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:51,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:52,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:53,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:54,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:55,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:56,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:57,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:58,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:59,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:60,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:61,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:62,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:63,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:64,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:65,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:66,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:67,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:68,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:69,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:70,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:71,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:72,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:73,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:74,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:75,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:76,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:77,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:78,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:79,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:80,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:81,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:82,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:83,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:84,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:85,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:86,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:87,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:88,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:89,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:90,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:91,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:92,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:93,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:94,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:95,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:96,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:97,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:99,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:100,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:101,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:102,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:103,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:104,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:105,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:106,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:107,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:108,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:109,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:110,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:111,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:112,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:113,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:114,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:115,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:116,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:117,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:118,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:119,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:120,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:121,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:122,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:123,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:124,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:125,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:126,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:127,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:128,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:129,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:130,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:131,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:132,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:133,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:134,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:135,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:136,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:137,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:138,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:139,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:140,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:141,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:142,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:143,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:144,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:145,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:146,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:147,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:148,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:149,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:150,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:151,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:152,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:153,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:154,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:155,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:156,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:157,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:158,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:159,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:160,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:161,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:162,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:163,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:164,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:165,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:166,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:167,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:168,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:169,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:170,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:171,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:172,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:173,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:174,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:175,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:176,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:177,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:178,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:179,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:180,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:181,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:182,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:183,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:184,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:185,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:186,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:187,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:188,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         },
//         {        
//           transactionId:189,
//           transactionType: "Enterprise Adjustment",
//           ratingType: "-",
//           earningDate: "4/3/2024",
//           dollarAmount:" 99.00 ",
//           property: "MSCT",
//           revenueCenter: "-",
//           balance: " 99.00 ",
//           earningTime: "-",
//           reason: "Deceased Patron",
//           details: "From #987651"
//         }  
// ]
